# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d5bb7aea00d16bd956dae458dccbbd6271106afdeefb2ae2ba730b0b2b1f0924bc8234c0460be04755ccf21459f6ee27614c0ea4b4602abe429fd49973677a45

test:
  secret_key_base: 1fa15397596d095c6200d9cd6c25a915f574bcc0c48070f1ba204ae8f476289af5edbc6cfb28bfed70a57c31c1390378190ea71600c1c9dedf10bc047231b0c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
